### ISSUE TITLE
Force users to explicitly set an ExceptionHandler on the Disruptor

### ISSUE THREAD

**Issue by juddgaddie** [LMAX-Exchange/disruptor-proxy#17]
The require to force users to explicitly set an ExceptionHandler on the Disruptor added originally here 6313bda712e4469e59fad1f7b3f8df3c07f677ab has been broken by this code change to the Disruptor LMAX-Exchange/disruptor/pull/125

The Disruptor Proxy reflectively checks if Disruptor::exceptionHandler is set. However it is now always set to a ExceptionHandlerWrapper which make the check invalid.

**Comment by epickrram** [comment]
So, is your issue that the check is always pass, regardless of whether the user has set a handler, and it should be removed?
Or is the issue that the code should be changed to check the wrapper state? That would add even more knowledge of the underlying library.

**Comment by epickrram** [comment]
So, is your issue that the check is always pass, regardless of whether the user has set a handler, and it should be removed?
Or is the issue that the code should be changed to check the wrapper state? That would add even more knowledge of the underlying library.
